### ISSUE TITLE
How can I run the live Bookshop editor locally?

### ISSUE THREAD

**Issue by Tkko** [CloudCannon/sendit-astro-template#12]
I run the app locally without any issue and it works great 👍, thanks for that.

The question I have is how can I run the live Bookshop editor locally or on a third party server?

I read this in the [docs](https://cloudcannon.com/documentation/guides/bookshop-eleventy-guide/) so I guess it's possible but I can't find a guide or additional info about it.

> we want to ensure that you aren't vendor-locked to our platform

**Comment by bglw** [comment]
👋 Bookshop's code is licensed open source, so there's no technical barrier to running it in another location. I don't believe an implementation of the live editing specifically exists outside of CloudCannon, though.

The primary goal there is that you aren't vendor-locked in a technical sense — i.e. building the site doesn't require calling some headless CMS API, and is instead self-contained.

Bookshop itself doesn't know how to edit content, such as modifying front matter, so it does need to paired with some tool that can handle the actual editing.
