### ISSUE TITLE
cms integration

### ISSUE THREAD

**Issue by wanghaisheng** [CloudCannon/sendit-astro-template#9]
can you add some cms integration  in the astro website mentioned

**Comment by AlyshaNolan** [comment]
Can you please elaborate what you mean by this? 😊

This site is optimised for editing within the CloudCannon CMS

**Comment by karyasuta** [comment]
Can you add other git-based CMS like DecapCMS?

**Comment by bglw** [comment]
Hey @karyasuta 

This template is open source so you're free to add integrations to your own copy! 

We make an effort to maintain the contents of our templates, which means we aren't able to merge in configurations for another CMS — without being users of that CMS we can't guarantee any compatibility.
